// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Relude_List = require("relude/src/Relude_List.bs.js");
var Relude_Array = require("relude/src/Relude_Array.bs.js");
var Decode_AsResult_OfParseError = require("bs-decode/src/Decode_AsResult_OfParseError.bs.js");

function make(name, mtimeMs) {
  return {
          name: name,
          mtimeMs: mtimeMs
        };
}

function encodeJson(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                param.name
              ],
              /* :: */[
                /* tuple */[
                  "mtimeMs",
                  param.mtimeMs
                ],
                /* [] */0
              ]
            ]);
}

function decodeJson(json) {
  return Curry._2(Decode_AsResult_OfParseError.Pipeline.run, json, Curry._3(Decode_AsResult_OfParseError.Pipeline.field, "mtimeMs", Decode_AsResult_OfParseError.Pipeline.floatFromNumber, Curry._3(Decode_AsResult_OfParseError.Pipeline.field, "name", Decode_AsResult_OfParseError.Pipeline.string, Curry._1(Decode_AsResult_OfParseError.Pipeline.succeed, make))));
}

var $$File = {
  make: make,
  encodeJson: encodeJson,
  decodeJson: decodeJson
};

function encodeJson$1(xs) {
  return Curry._2(Relude_Array.map, (function (param) {
                return Json_encode.object_(/* :: */[
                            /* tuple */[
                              "name",
                              param[0]
                            ],
                            /* :: */[
                              /* tuple */[
                                "files",
                                Json_encode.array(encodeJson, param[1])
                              ],
                              /* [] */0
                            ]
                          ]);
              }), Relude_List.toArray(xs));
}

var decodeArray = Curry._1(Relude_Array.map, (function (x) {
        return /* tuple */[
                Curry._2(Decode_AsResult_OfParseError.tuple, Decode_AsResult_OfParseError.string, Curry._1(Decode_AsResult_OfParseError.array, decodeJson)),
                x
              ];
      }));

var Workspaces = {
  encodeJson: encodeJson$1,
  decodeArray: decodeArray
};

var Decode;

exports.Decode = Decode;
exports.$$File = $$File;
exports.Workspaces = Workspaces;
/* decodeArray Not a pure module */
