// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var Relude_List = require("relude/src/Relude_List.bs.js");
var Relude_Array = require("relude/src/Relude_Array.bs.js");

function encodeJson(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                param.name
              ],
              /* :: */[
                /* tuple */[
                  "mtimeMs",
                  param.mtimeMs
                ],
                /* [] */0
              ]
            ]);
}

var $$File = {
  encodeJson: encodeJson
};

function encodeJson$1(xs) {
  return Curry._2(Relude_Array.map, (function (param) {
                return Json_encode.object_(/* :: */[
                            /* tuple */[
                              "name",
                              param[0]
                            ],
                            /* :: */[
                              /* tuple */[
                                "files",
                                Json_encode.array(encodeJson, param[1])
                              ],
                              /* [] */0
                            ]
                          ]);
              }), Relude_List.toArray(xs));
}

var Workspaces = {
  encodeJson: encodeJson$1
};

exports.$$File = $$File;
exports.Workspaces = Workspaces;
/* Relude_List Not a pure module */
